services:
  stats-db:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_DB: statsdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
    ports:
      - "6541:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: stats-db

  stats-server:
    build:
      context: ./stats-service/stats-server
      dockerfile: Dockerfile
    image: stats-server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsdb
      - STATS_SERVER_URL=http://stats-server:9090
    command: ["java", "-jar", "/app/app.jar"]
    container_name: stats-server

  ewm-service:
    build: ./ewm-service
    image: ewm-server
    container_name: ewm-server
    depends_on:
      - ewm-db
      - stats-server
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - STATS_SERVER_URL=http://stats-server:9090


  ewm-db:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_DB: ewm
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"  # 5432 для IDEA
    volumes:
      - ewm_postgres_data:/var/lib/postgresql/data
    container_name: ewm-db

volumes:
  postgres_data:
  ewm_postgres_data: