services:
  stats-db:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_DB: statsdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: stats-db

  stats-server:
    build:
      context: ./stats-service/stats-server
      dockerfile: Dockerfile
    image: stats-server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
    command: ["java", "-jar", "/app/app.jar"]
    volumes:
      - ./stats-service/target:/app
    container_name: stats-server

volumes:
  postgres_data:


#  ewm-service:
#    build: ewm-service
#    image: ewm-server
#    container_name: ewm-server
#    ports:
#      - "8080:8080"
##    depends_on:
##      - ewm-db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/ewm
#      - SPRING_DATASOURCE_USERNAME=user
#      - SPRING_DATASOURCE_PASSWORD=12345

#  ewm-db:
#    image: postgres:16.1
